### ISSUE TITLE
[SUGGESTION] Vertical SubClaiming

### ISSUE THREAD

**Issue by ShaneBeee** [TechFortress/GriefPrevention#269]
Hello
I would like to suggest vertical subclaims. Example, being able to claim say a 10x10 area, but also with a Y value of say 10. This way you could stack subclaims, like if you were doing condos/apartments in your little town.

I personally would LOVE to have this feature on my server.
Thanks for reading!

**Comment by bigpresh** [comment]
This has been suggested in the past, and I believe it was rejected because it would be too expensive to check.

It *might* be less expensive if "stackability" only applied to subclaims, rather than top-level claims, perhaps.

I'm not sure how creating and visualising stacked claims could be done in a non-confusing manner.  Maybe a command that limits the height of a subclaim to be created, e.g. `/subclaimheight 10`, which you'd use before creating it, and it would treat the claim as being from the Y-value of the block you right click first to that many blocks above it.

I definitely see the appeal, though!

**Comment by ShaneBeee** [comment]
Well... I totally thought I replied to this. Yeah I was referring STRICTLY to subclaims. As stacking top level claims would make absolutely no sense. 
I Feel like I have been in a few situations where vertical sub claiming would be handy dandy. Like I have a room in my house I want to give someone Perm to, but I dont want them to be able to access the chests on the lower floor. 
And I know a lot of my players would love this, especially since I have the GP Real Estate addon.... would be able to do a lot more.
If I knew how to write java, I would be ALL over this ;)

**Comment by LadyViviann** [comment]
This would be very handy for the crew building a subway system on our server as well where people would like to give perms to the builders, but if the perms are taken away after the build and someone gets out of their minecart, they can't get back in it again. Or they are left with access to the entire build.

**Comment by FrozenBeard** [comment]
If you are doing rentable condos/apartments, you can make it work with areashop to rent vertical regions using worldguard. I use this for my shops.

**Comment by Weasel-Beans** [comment]
This would definitely be helpful for what I'm doing with claims in the spawn area of my server
